// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"
)

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE sku = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, sku string) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, sku)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT sku, title, pricecents FROM products WHERE sku = ?
`

func (q *Queries) GetProduct(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, sku)
	var i Product
	err := row.Scan(&i.Sku, &i.Title, &i.Pricecents)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT sku, title, pricecents FROM products
`

func (q *Queries) GetProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(&i.Sku, &i.Title, &i.Pricecents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (sku, title, priceCents) VALUES (?, ?, ?) RETURNING sku
`

type InsertProductParams struct {
	Sku        string
	Title      string
	Pricecents int64
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (string, error) {
	row := q.db.QueryRowContext(ctx, insertProduct, arg.Sku, arg.Title, arg.Pricecents)
	var sku string
	err := row.Scan(&sku)
	return sku, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products SET title = ?, priceCents = ? WHERE sku = ?
`

type UpdateProductParams struct {
	Title      string
	Pricecents int64
	Sku        string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct, arg.Title, arg.Pricecents, arg.Sku)
	return err
}
